### ISSUE TITLE
Repeated item

### ISSUE THREAD

**Issue by apinanyogaratnam** [BushelScript/help#4]
<img width="173" alt="Screen Shot 2021-06-29 at 5 11 01 PM" src="https://user-images.githubusercontent.com/72412733/123867917-fe048780-d8fc-11eb-9eed-3f32f6dc02b7.png">
<img width="230" alt="Screen Shot 2021-06-29 at 5 13 33 PM" src="https://user-images.githubusercontent.com/72412733/123868173-576cb680-d8fd-11eb-8545-e776949fca36.png">

Not sure if this is intentional or not (https://bushelscript.github.io/help/docs/ref/basic-syntax)

Edit: Seems like this is intentional

**Comment by ThatsJustCheesy** [comment]
Indeed intentional, though in all honestly that list should probably be pruned down some.
